//
// Created by AbeChaudry on 4/15/20.
//

#ifndef FIRMWARE_REBELS_ROBOT_INFRAREDSENSOR1_H
#define FIRMWARE_REBELS_ROBOT_INFRAREDSENSOR1_H

#define IR_SENSOR	15

void initializeIR1();
void * getSpeedIR1();

#endif //FIRMWARE_REBELS_ROBOT_INFRAREDSENSOR1_H
